############################
## NAVIGATION MENU
############################

main:
  - name: About
    url: '/en/#'
    weight: 10
  - name: Publications
    url: '/en/#publications'
    weight: 20
  - name: Projects
    url: '/en/#projects'
    weight: 30
  - name: Teaching
    url: '/en/#teaching'
    weight: 40
  - name: CV
    url: '/en/cv/'
    weight: 50
  - name: Contact
    url: '/en/#contact'
    weight: 60
