############################
## NAVIGATION MENU
############################

main:
  - name: À propos
    url: '/#'
    weight: 10
  - name: Publications
    url: '/#publications'
    weight: 20
  - name: Projets
    url: '/#projects'
    weight: 30
  - name: Enseignement
    url: '/#teaching'
    weight: 40
  - name: CV
    url: '/cv/'
    weight: 50
  - name: Contact
    url: '/#contact'
    weight: 60
